server:
  port: 63085
spring:
  application:
    name: lore
gcp:
  bucket:
    name: ${BUCKET:year-exp-project}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka}